import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  partidas: defineTable({
    nivel: v.number(),
    nombre: v.string(),
    familia: v.string(),
    sub_partida: v.string(),
    partida_nombre: v.optional(v.string()), // Reference to parent partida for nivel 2 & 3
    unidad: v.string(),
    cantidad: v.number(),
    precio_unitario: v.number(),        
    presupuesto_original: v.number(),
    presupuesto_aprobado: v.number(),
    pagado: v.number(),    
    por_gastar: v.optional(v.number()),
    archivo_origen: v.string(),
    proyecto: v.optional(v.id("desarrollos")),
  }).index("by_proyecto", { fields: ["proyecto"] }),
  desarrollos: defineTable({
    nombre: v.string(),
    descripcion: v.string(),
    image: v.string(),
  }),
  pagos: defineTable({
    partida_id: v.id("partidas"),
    administracion: v.string(),
    partida: v.string(),
    familia: v.string(),
    sub_partida: v.string(),
    monto: v.number(),
    fecha: v.string(),
    tipo_pago: v.string(),
    tarjeta: v.string(),
    banco: v.string(),
    tipo_cambio: v.string(),
    moneda: v.string(),
    logo_banco: v.string(),
    numero_cuenta: v.string(),
    numero_transferencia: v.string(),
    proyecto: v.id("desarrollos"),
    status: v.optional(v.string()),
    codigo_referencia: v.string(),
    factura: v.optional(v.string()),
    comprobante: v.optional(v.string()),
    presupuesto_archivo: v.optional(v.string()),
  }).index("by_administracion", { fields: ["administracion"] }).index("by_partida", { fields: ["partida"] }).index("by_familia", { fields: ["familia"] }).index("by_sub_partida", { fields: ["sub_partida"] }),
  documentos: defineTable({
    nombre: v.string(),
    descripcion: v.string(),
    image: v.string(),
    type: v.string(),
    pago_ids: v.array(v.id("pagos")),
    proyecto: v.id("desarrollos"),
  }).index("by_proyecto", { fields: ["proyecto"] }),
  meticas_presupuesto: defineTable({
    proyecto: v.id("desarrollos"),
    presupuesto_original: v.number(),
    presupuesto_aprobado: v.number(),
    gasto_total: v.number(),
    por_gastar: v.number(),    
  }).index("by_proyecto", { fields: ["proyecto"] }),
});
