import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  partidas: defineTable({
    nombre: v.string(),
    familia: v.string(),
    sub_partida: v.string(),
    Cantidad: v.string(),
    PrecioUnitario: v.string(),
    Subtotal: v.string(),
    Iva: v.string(),
    total: v.string(),
    aprobado: v.string(),
    pagado: v.string(),
    por_liquidar: v.string(),
    actual: v.string(),
    fecha_carga: v.string(),
    archivo_origen: v.string(),
  }),
  desarrollos: defineTable({
    nombre: v.string(),
    image: v.string(),
  }),
  costos: defineTable({
    administracion: v.string(),
    partida: v.string(),
    familia: v.string(),
    sub_partida: v.string(),
    monto: v.string(),
    monto_decimal: v.optional(v.number()),
    fecha: v.string(),
    codigo_referencia: v.string(),
    factura: v.string(),
  }).index("by_administracion", { fields: ["administracion"] }).index("by_partida", { fields: ["partida"] }).index("by_familia", { fields: ["familia"] }).index("by_sub_partida", { fields: ["sub_partida"] }),
  pagos: defineTable({
    administracion: v.string(),
    partida: v.string(),
    familia: v.string(),
    sub_partida: v.string(),
    monto: v.string(),
    fecha: v.string(),
    tipo_pago: v.string(),
    tarjeta: v.string(),
    banco: v.string(),
    tipo_cambio: v.string(),
    moneda: v.string(),
    logo_banco: v.string(),
    numero_cuenta: v.string(),
    numero_transferencia: v.string(),
    codigo_referencia: v.string(),
    factura: v.string(),
    informacion_facturacion_pago: v.optional(v.id("informacion_facturacion_pago")),
  }).index("by_administracion", { fields: ["administracion"] }).index("by_partida", { fields: ["partida"] }).index("by_familia", { fields: ["familia"] }).index("by_sub_partida", { fields: ["sub_partida"] }),
  informacion_facturacion_pago: defineTable({
    calle: v.string(),
    colonia: v.string(),
    municipio: v.string(),
    estado: v.string(),
    codigo_postal: v.string(),
    rfc: v.string(),
    razon_social: v.string(),
    telefono: v.string(),
    correo: v.string(),
  }),
});
